### ISSUE TITLE
Add promql-mode to MELPA?

### ISSUE THREAD

**Issue by dgellow** [Andor/promql-mode#3]
Hi @Andor,

I would like to be able to install and update your mode directly from emacs. Would you consider adding your project to [MELPA](https://github.com/melpa/melpa), the community based archive of Emacs packages?

**Comment by Andor** [comment]
@dgellow This module still in the not-very-good state. But if you think it can be helpful for anyone - you can create PR to https://github.com/melpa/melpa by yourself.
Maybe I will continue my work with this module, but I can't guarantee it.
